FROM ubuntu:latest
ENV VERSION=1.2.0

RUN apt-get update
RUN apt install python3 -y
RUN apt-get install vim zip unzip

WORKDIR /usr/app/src

COPY print.py ./
COPY zip_job.py /tmp/

ENTRYPOINT ["python","./zip_job.py"]
