FROM ubuntu:latest

ENV VERSION=1.2.0

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install vim -y 
RUN apt-get install zip -y
RUN apt-get install unzip -y

COPY root/Desktop/Project1/zip_job.py /tmp
WORKDIR /tmp/

CMD ["docker" , "echo info | grep OStype"]
CMD ["docker" , "echo info | grep Architecture"]
CMD ["echo" , "uname -a"]
# CMD ["docker" , "exec -it $containerId test -f /tmp/zip_job.py"]
