FROM ubuntu:latest

ENV VERSION=1.2.0

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install vim -y 
RUN apt-get install zip -y
RUN apt-get install unzip -y
WORKDIR /tmp/
COPY zip_job.py . /tmp/
CMD ["python3" , "./zip_job.py]
CMD ["docker" , "chmod +x /tmp/zip_job.py" ]

CMD ["docker" , "echo info | grep OStype"]
CMD ["docker" , "echo info | grep Architecture"]
CMD ["echo" , "uname -a"]
# CMD ["docker" , "exec -it $containerId test -f /tmp/zip_job.py"]
